### ISSUE TITLE
(OCoLC) prefix handling

### ISSUE THREAD

**Issue by klinga** [BookOps-CAT/bookops-worldcat#103]
https://github.com/BookOps-CAT/bookops-worldcat/blob/6a865bb91dbbcd6a4bea5773df113fd479cccf33/bookops_worldcat/utils.py#L17-L37

What do you think about adding a functionality to remove the "(OCoLC)" prefix as it is recorded in the 035 MARC tag?
This may be more common to record the OCLC # in this tag instead of a local control field (001).

**Comment by charlottekostelic** [comment]
@klinga, I think that makes a lot of sense! I can add this to v1.0.1.

**Comment by klinga** [comment]
@charlottekostelic Thank you!
