### ISSUE TITLE
Metadata API 2.0 changes

### ISSUE THREAD

**Issue by klinga** [BookOps-CAT/bookops-worldcat#63]
Worldcat Metdata API 2.0 introduced on May 8, 2023 will supersede v. 1.x on April 30, 2024.
https://developer.api.oclc.org/wc-metadata-v2

The new release changes the base URL for the services and introduces new functionality. Will requre extensive refactoring.
Plans to work on in during the summer '23.

**Comment by harrylloyd-bl** [comment]
Hi @klinga we're using bookops-worldcat to access the metadata API for a project at the British Library converting physical catalogue cards into digital records and I'm keen to help with the API v2.0 refactor. There's obviously a lot to do in metadata_api.py and test_metadata_api.py but I did start working through it. Is this something you've got any bandwidth to look at or has it fallen by the wayside?

**Comment by klinga** [comment]
Hi @harrylloyd-bl 
My colleague @charlottekostelic and I are currently working on the upgrade to API 2.0. There are few PR in the pipeline that should give you an idea what our direction is. Due to significant differences in the new API we won't be able to keep backward compatibility and the new version of the wrapper will include breaking changes. 
We should be done with majority of the work early next week. Maybe then it would be a good time for your contributions? Your help would be much appreciated. Maybe there are specific endpoints not covered by us that you would like to include? Any ideas and suggestions are welcome!
